import express, { Application } from "express";
import "express-async-errors";
const cors = require("cors");
import { handleErrors } from "./error";
import { userRoutes } from "./routes/user.routes";
import { teamRoutes } from "./routes/team.routes";
import { leagueRoutes } from "./routes/league.routes";
import { stadiumRoutes } from "./routes/stadium.routes";
import { formationRoutes } from "./routes/formation.routes";
import { nationalityRoutes } from "./routes/nationality.routes";
import { playerRoutes } from "./routes/player.routes";
import { languageMiddleware } from "./middlewares/language.middleware";
import { specialAbilityRoutes } from "./routes/special-ability.routes";
import { abilityRoutes } from "./routes/ability.routes";
import { positionCategoryRoutes } from "./routes/position-category.routes";
import { positionRoutes } from "./routes/position.routes";
import { appearanceRoutes } from "./routes/appearance.routes";
import { settingRoutes } from "./routes/setting.routes";

const app: Application = express();
app.use(express.json());
app.use(cors());
app.use(languageMiddleware);
app.use("/user", userRoutes);
app.use("/team", teamRoutes);
app.use("/league", leagueRoutes);
app.use("/stadium", stadiumRoutes);
app.use("/formation", formationRoutes);
app.use("/nationality", nationalityRoutes);
app.use("/player", playerRoutes);
app.use("/special-ability", specialAbilityRoutes);
app.use("/ability", abilityRoutes);
app.use("/position", positionRoutes);
app.use("/position-category", positionCategoryRoutes);
app.use("/appearance", appearanceRoutes);
app.use("/setting", settingRoutes);

app.use(handleErrors);
export default app;
